### ISSUE TITLE
Drake crashes when listing tasks with no description

### ISSUE THREAD

**Issue by philc** [srackham/drake#18]
Drake file:

```
#!/usr/bin/env deno run --allow-read --allow-write --allow-env --allow-net --allow-run
import { desc, run, task, sh } from "https://deno.land/x/drake@v1.5.1/mod.ts";
task("hello", [], () => {});
run();
```

Running this with `-l` produces:

```
error: Uncaught (in promise) TypeError: Reduce of empty array with no initial value
    const maxLen = keys.reduce(function (a, b) {
                        ^
    at Array.reduce (<anonymous>)
    at TaskRegistry.list (https://deno.land/x/drake@v1.5.1/lib/tasks.ts:275:25)
    at run (https://deno.land/x/drake@v1.5.1/lib/registry.ts:45:18)
```

If `desc` is called prior to `task`, then there is no error when listing tasks.

Expected: drake -l should be able to list defined tasks which do not have descriptions.

**Comment by srackham** [comment]
Fixed: 296a164
